name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   
  workflow_dispatch:     
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: MayelaLopez28
          outputs: dist/snake.svg
          snake_color: "#9b59b6"    
          background: "#0d1117"     

      - name: Push Snake
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
