name: GitHub Snake

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate GitHub Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=purple&color_dots=#e0b3ff,#c080ff,#a64dff,#8f00ff,#6600cc

      - name: Commit GitHub Snake
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add dist/github-snake.svg
          git commit -m "Update GitHub Snake" || echo "No changes to commit"
          git push
